spring:
  datasource:
    url: jdbc:mysql://next-is-us-db.cnfnmk8c498x.ap-northeast-2.rds.amazonaws.com:3306/next_is_us_db
    username: admin
    password: S3cureP0ssw0rd!=

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true