spring:
  application:
    name: project

  profiles:
    active: deploy

  security:
    user:
      name: admin
      password: S3cureP@ssw0rd!
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 2592000000 # 1 month



cloud:
  aws:
    s3:
      bucket: todays-mom-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3SUSXNPNEH7MTUFE
      secret-key: 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