spring:
  application:
    name: project

  jackson:
    time-zone: Asia/Seoul

  profiles:
    active: deploy

  security:
    user:
      name: admin
      password: S3cureP@ssw0rd!

  mail:
    host: smtp.gmail.com
    port: 587
    username: today.mom.love@gmail.com
    password: xbyw syis uoru dpbq
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 2592000000 # 1 month

cloud:
  aws:
    s3:
      bucket: todays-mom-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3SUSXNPNEH7MTUFE
      secret-key: 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

logging:
  level:
    root: info