spring:
  datasource:
    url: jdbc:mysql://localhost:3306/next_is_us
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true